// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneShop.Data.EF;

#nullable disable

namespace PhoneShop.Data.Migrations
{
    [DbContext(typeof(PhoneShopDbContext))]
    [Migration("20241118160344_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhoneShop.Data.Entities.Category", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("C_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"), 1L, 1);

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("C_Name");

                    b.Property<int?>("CParentId")
                        .HasColumnType("int")
                        .HasColumnName("C_ParentId");

                    b.Property<int>("CSortOrder")
                        .HasColumnType("int")
                        .HasColumnName("C_SortOrder");

                    b.HasKey("CId");

                    b.ToTable("tbCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CId = 1,
                            CName = "Flagship",
                            CSortOrder = 1
                        },
                        new
                        {
                            CId = 2,
                            CName = "Mid-range",
                            CSortOrder = 2
                        },
                        new
                        {
                            CId = 3,
                            CName = "Apple iPhone Pro series",
                            CParentId = 1,
                            CSortOrder = 1
                        },
                        new
                        {
                            CId = 4,
                            CName = "Samsung Galaxy S series",
                            CParentId = 1,
                            CSortOrder = 2
                        },
                        new
                        {
                            CId = 5,
                            CName = "Samsung Galaxy A series",
                            CParentId = 2,
                            CSortOrder = 3
                        },
                        new
                        {
                            CId = 6,
                            CName = "OnePlus 9 series",
                            CParentId = 1,
                            CSortOrder = 1
                        },
                        new
                        {
                            CId = 7,
                            CName = "Xiaomi Mi series",
                            CParentId = 1,
                            CSortOrder = 2
                        },
                        new
                        {
                            CId = 8,
                            CName = "OPPO Reno series",
                            CParentId = 1,
                            CSortOrder = 3
                        },
                        new
                        {
                            CId = 9,
                            CName = "Huawei P series",
                            CParentId = 1,
                            CSortOrder = 4
                        },
                        new
                        {
                            CId = 10,
                            CName = "LG G series",
                            CParentId = 1,
                            CSortOrder = 5
                        },
                        new
                        {
                            CId = 11,
                            CName = "Samsung Galaxy Note series",
                            CParentId = 4,
                            CSortOrder = 1
                        },
                        new
                        {
                            CId = 12,
                            CName = "Samsung Galaxy Fold series",
                            CParentId = 4,
                            CSortOrder = 2
                        },
                        new
                        {
                            CId = 13,
                            CName = "Samsung Galaxy Z series",
                            CParentId = 4,
                            CSortOrder = 3
                        },
                        new
                        {
                            CId = 14,
                            CName = "Xiaomi Redmi series",
                            CParentId = 2,
                            CSortOrder = 1
                        },
                        new
                        {
                            CId = 15,
                            CName = "Realme series",
                            CParentId = 2,
                            CSortOrder = 2
                        },
                        new
                        {
                            CId = 16,
                            CName = "Nokia X series",
                            CParentId = 2,
                            CSortOrder = 3
                        });
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Customer", b =>
                {
                    b.Property<int>("CusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cus_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CusId"), 1L, 1);

                    b.Property<string>("CusAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Cus_Address");

                    b.Property<string>("CusEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Cus_Email");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Cus_Name");

                    b.Property<string>("CusPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Cus_Phone");

                    b.HasKey("CusId");

                    b.ToTable("tbCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            CusId = 1,
                            CusAddress = "123 Main St",
                            CusEmail = "john.doe@example.com",
                            CusName = "John Doe",
                            CusPhone = "555-1234"
                        },
                        new
                        {
                            CusId = 2,
                            CusAddress = "456 Park Ave",
                            CusEmail = "jane.smith@example.com",
                            CusName = "Jane Smith",
                            CusPhone = "555-5678"
                        },
                        new
                        {
                            CusId = 3,
                            CusAddress = "789 Elm St",
                            CusEmail = "bob.johnson@example.com",
                            CusName = "Bob Johnson",
                            CusPhone = "555-9012"
                        },
                        new
                        {
                            CusId = 4,
                            CusAddress = "321 Oak Ln",
                            CusEmail = "ann.lee@example.com",
                            CusName = "Ann Lee",
                            CusPhone = "555-3456"
                        },
                        new
                        {
                            CusId = 5,
                            CusAddress = "654 Maple Rd",
                            CusEmail = "tom.wilson@example.com",
                            CusName = "Tom Wilson",
                            CusPhone = "555-7890"
                        },
                        new
                        {
                            CusId = 6,
                            CusAddress = "246 Pine St",
                            CusEmail = "mary.brown@example.com",
                            CusName = "Mary Brown",
                            CusPhone = "555-2468"
                        },
                        new
                        {
                            CusId = 7,
                            CusAddress = "135 Oak Ave",
                            CusEmail = "david.lee@example.com",
                            CusName = "David Lee",
                            CusPhone = "555-1357"
                        },
                        new
                        {
                            CusId = 8,
                            CusAddress = "789 Maple St",
                            CusEmail = "sarah.davis@example.com",
                            CusName = "Sarah Davis",
                            CusPhone = "555-7891"
                        },
                        new
                        {
                            CusId = 9,
                            CusAddress = "246 Elm St",
                            CusEmail = "mike.johnson@example.com",
                            CusName = "Mike Johnson",
                            CusPhone = "555-2468"
                        },
                        new
                        {
                            CusId = 10,
                            CusAddress = "135 Park Ave",
                            CusEmail = "lisa.smith@example.com",
                            CusName = "Lisa Smith",
                            CusPhone = "555-1357"
                        },
                        new
                        {
                            CusId = 11,
                            CusAddress = "789 Maple Rd",
                            CusEmail = "daniel.wilson@example.com",
                            CusName = "Daniel Wilson",
                            CusPhone = "555-7891"
                        },
                        new
                        {
                            CusId = 12,
                            CusAddress = "246 Oak Ln",
                            CusEmail = "jessica.lee@example.com",
                            CusName = "Jessica Lee",
                            CusPhone = "555-2468"
                        },
                        new
                        {
                            CusId = 13,
                            CusAddress = "135 Pine St",
                            CusEmail = "mark.brown@example.com",
                            CusName = "Mark Brown",
                            CusPhone = "555-1357"
                        },
                        new
                        {
                            CusId = 14,
                            CusAddress = "789 Park Ave",
                            CusEmail = "emily.davis@example.com",
                            CusName = "Emily Davis",
                            CusPhone = "555-7891"
                        },
                        new
                        {
                            CusId = 15,
                            CusAddress = "246 Elm St",
                            CusEmail = "andrew.johnson@example.com",
                            CusName = "Andrew Johnson",
                            CusPhone = "555-2468"
                        },
                        new
                        {
                            CusId = 16,
                            CusAddress = "135 Maple Rd",
                            CusEmail = "rachel.smith@example.com",
                            CusName = "Rachel Smith",
                            CusPhone = "555-1357"
                        });
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Manufacturer", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("M_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MId"), 1L, 1);

                    b.Property<string>("MAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("M_Address");

                    b.Property<string>("MEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("M_Email");

                    b.Property<string>("MName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("M_Name");

                    b.Property<string>("MPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("M_Phone");

                    b.HasKey("MId");

                    b.ToTable("tbManufacturer", (string)null);

                    b.HasData(
                        new
                        {
                            MId = 1,
                            MAddress = "129 Samsung-ro, Yeongtong-gu, Suwon-si, Gyeonggi-do, Korea",
                            MEmail = "support@Samsung.com",
                            MName = "SamSung",
                            MPhone = "+82-31-279-9577"
                        },
                        new
                        {
                            MId = 2,
                            MAddress = "1 Apple Park Way, Cupertino, CA 95014, USA",
                            MEmail = "info@apple.com",
                            MName = "Apple",
                            MPhone = "+1 (408) 996-1010"
                        },
                        new
                        {
                            MId = 3,
                            MAddress = "Bantian, Longgang District, Shenzhen, China",
                            MEmail = "support@oneplus.com",
                            MName = "OnePlus",
                            MPhone = "+86-755-28780808"
                        },
                        new
                        {
                            MId = 4,
                            MAddress = "Building 3, Wangjing Park, Chaoyang District, Beijing, China",
                            MEmail = "service.global@xiaomi.com",
                            MName = "Xiaomi",
                            MPhone = "+86-400-100-5678"
                        },
                        new
                        {
                            MId = 5,
                            MAddress = "1600 Amphitheatre Parkway, Mountain View, California 94043, United States of America",
                            MEmail = "support@google.com",
                            MName = "OPPO",
                            MPhone = "+1 650-253-0000"
                        },
                        new
                        {
                            MId = 6,
                            MAddress = "Bantian, Longgang District, Shenzhen, China",
                            MEmail = "support@huawei.com",
                            MName = "Huawei",
                            MPhone = "+86-755-28780808"
                        },
                        new
                        {
                            MId = 7,
                            MAddress = "1-7-1 Konan, Minato-ku, Tokyo 108-0075, Japan",
                            MEmail = "support@sony.com",
                            MName = "Sony",
                            MPhone = "+81-3-6748-2111"
                        },
                        new
                        {
                            MId = 8,
                            MAddress = "128 Yeoui-daero, Yeongdeungpo-gu, Seoul, 07336, South Korea",
                            MEmail = "support@lg.com",
                            MName = "LG",
                            MPhone = "+82-2-3777-1114"
                        },
                        new
                        {
                            MId = 9,
                            MAddress = "Karaportti 3, 02610 Espoo, Finland",
                            MEmail = "support@nokia.com",
                            MName = "Nokia",
                            MPhone = "+358 (0) 10 44 88 000"
                        },
                        new
                        {
                            MId = 10,
                            MAddress = "222 W Merchandise Mart Plaza #1800, Chicago, IL 60654, USA",
                            MEmail = "support@motorola.com",
                            MName = "Motorola",
                            MPhone = "+1 (800) 668-6765"
                        },
                        new
                        {
                            MId = 11,
                            MAddress = "No. 15 Li-De Rd., Beitou District, Taipei 112, Taiwan",
                            MEmail = "support@asus.com",
                            MName = "Asus",
                            MPhone = "+886-2-2894-3447"
                        },
                        new
                        {
                            MId = 12,
                            MAddress = "Morrisville, NC 27560, United States",
                            MEmail = "support@lenovo.com",
                            MName = "Lenovo",
                            MPhone = "+1-800-426-7378"
                        },
                        new
                        {
                            MId = 13,
                            MAddress = "1600 Amphitheatre Parkway, Mountain View, California 94043, United States of America",
                            MEmail = "support@google.com",
                            MName = "Google",
                            MPhone = "+1 650-253-0000"
                        },
                        new
                        {
                            MId = 14,
                            MAddress = "No. 1 Building, Shangdi Xinxi Road, Haidian District, Beijing, China",
                            MEmail = "support@vivo.com",
                            MName = "Vivo",
                            MPhone = "+86-755-28780808"
                        });
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Order", b =>
                {
                    b.Property<int>("OId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("O_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OId"), 1L, 1);

                    b.Property<int>("CusId")
                        .HasColumnType("int")
                        .HasColumnName("Cus_ID");

                    b.Property<DateTime>("ODate")
                        .HasColumnType("date")
                        .HasColumnName("O_Date");

                    b.Property<int>("OStatus")
                        .HasColumnType("int")
                        .HasColumnName("O_Status");

                    b.HasKey("OId");

                    b.HasIndex("CusId");

                    b.ToTable("tbOrder", (string)null);
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("PId")
                        .HasColumnType("int")
                        .HasColumnName("P_ID");

                    b.Property<int>("OId")
                        .HasColumnType("int")
                        .HasColumnName("O_ID");

                    b.Property<decimal>("ODPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("OD_Price");

                    b.Property<int>("ODQuantity")
                        .HasColumnType("int")
                        .HasColumnName("OD_Quantity");

                    b.HasKey("PId", "OId");

                    b.HasIndex("OId");

                    b.ToTable("tbOrder_Detail", (string)null);
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Product", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("P_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"), 1L, 1);

                    b.Property<int>("MId")
                        .HasColumnType("int")
                        .HasColumnName("M_Id");

                    b.Property<string>("PAvatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("P_Avatar");

                    b.Property<string>("PBatteryCapacity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_BatteryCapacity");

                    b.Property<string>("PCamera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Camera");

                    b.Property<string>("PColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Color");

                    b.Property<string>("PConnectivity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Connectivity");

                    b.Property<string>("PDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("P_Description");

                    b.Property<string>("PDimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Dimension");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Name");

                    b.Property<string>("POperatingSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Operating_System");

                    b.Property<decimal>("POriginalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("P_OriginalPrice");

                    b.Property<decimal>("PPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("P_Price");

                    b.Property<string>("PRam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Ram");

                    b.Property<string>("PResolution")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Resolution");

                    b.Property<string>("PScreenSize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Screen_Size");

                    b.Property<int>("PStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("P_Stock");

                    b.Property<string>("PStorage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Storage");

                    b.Property<string>("PWeight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Weights");

                    b.HasKey("PId");

                    b.HasIndex("MId");

                    b.ToTable("tbProduct", (string)null);

                    b.HasData(
                        new
                        {
                            PId = 1,
                            MId = 1,
                            PAvatar = "1.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Quad camera: 108 MP + 10 MP + 10 MP + 12 MP",
                            PColor = "Phantom Black",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Samsung",
                            PDimension = "165.1 x 75.6 x 8.9 mm",
                            PName = "Samsung Galaxy S21 Ultra",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 1399m,
                            PPrice = 1199m,
                            PRam = "12 GB",
                            PResolution = "3200 x 1440 pixels",
                            PScreenSize = "6.8 inches",
                            PStock = 50,
                            PStorage = "256 GB",
                            PWeight = "227 g"
                        },
                        new
                        {
                            PId = 2,
                            MId = 2,
                            PAvatar = "2.jpg",
                            PBatteryCapacity = "3095 mAh",
                            PCamera = "Triple camera: 12 MP + 12 MP + 12 MP",
                            PColor = "Graphite",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Apple",
                            PDimension = "146.7 x 71.5 x 7.7 mm",
                            PName = "iPhone 13 Pro",
                            POperatingSystem = "iOS 15",
                            POriginalPrice = 1099m,
                            PPrice = 999m,
                            PRam = "6 GB",
                            PResolution = "2532 x 1170 pixels",
                            PScreenSize = "6.1 inches",
                            PStock = 30,
                            PStorage = "128 GB",
                            PWeight = "204 g"
                        },
                        new
                        {
                            PId = 3,
                            MId = 3,
                            PAvatar = "3.jpg",
                            PBatteryCapacity = "4500 mAh",
                            PCamera = "Triple camera: 50 MP + 8 MP + 2 MP",
                            PColor = "Gray Sierra",
                            PConnectivity = "5G",
                            PDescription = "Mid-range phone from OnePlus",
                            PDimension = "158.9 x 73.2 x 8.3 mm",
                            PName = "OnePlus Nord 2",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 429m,
                            PPrice = 399m,
                            PRam = "8 GB",
                            PResolution = "2400 x 1080 pixels",
                            PScreenSize = "6.43 inches",
                            PStock = 100,
                            PStorage = "128 GB",
                            PWeight = "189 g"
                        },
                        new
                        {
                            PId = 4,
                            MId = 4,
                            PAvatar = "4.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Quad camera: 64 MP + 8 MP + 2 MP + 2 MP",
                            PColor = "Onyx Gray",
                            PConnectivity = "4G",
                            PDescription = "Mid-range phone from Xiaomi",
                            PDimension = "164.1 x 76.9 x 8.5 mm",
                            PName = "Xiaomi Redmi Note 11 Pro",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 349m,
                            PPrice = 299m,
                            PRam = "6 GB",
                            PResolution = "2400 x 1080 pixels",
                            PScreenSize = "6.67 inches",
                            PStock = 150,
                            PStorage = "64 GB",
                            PWeight = "193 g"
                        },
                        new
                        {
                            PId = 5,
                            MId = 5,
                            PAvatar = "5.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Triple camera: 13 MP + 2 MP + 2 MP",
                            PColor = "Crystal Black",
                            PConnectivity = "4G",
                            PDescription = "Budget phone from OPPO",
                            PDimension = "163.6 x 75.7 x 8.4 mm",
                            PName = "OPPO A54",
                            POperatingSystem = "Android 10",
                            POriginalPrice = 249m,
                            PPrice = 199m,
                            PRam = "4 GB",
                            PResolution = "1600 x 720 pixels",
                            PScreenSize = "6.51 inches",
                            PStock = 200,
                            PStorage = "128 GB",
                            PWeight = "192 g"
                        },
                        new
                        {
                            PId = 6,
                            MId = 6,
                            PAvatar = "6.jpg",
                            PBatteryCapacity = "4400 mAh",
                            PCamera = "Quad camera: 50 MP + 64 MP + 13 MP + 40 MP",
                            PColor = "Mystic Silver",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Huawei",
                            PDimension = "163.8 x 75.8 x 8.6 mm",
                            PName = "Huawei Mate 50 Pro",
                            POperatingSystem = "Android 12",
                            POriginalPrice = 1499m,
                            PPrice = 1299m,
                            PRam = "12 GB",
                            PResolution = "2772 x 1344 pixels",
                            PScreenSize = "6.76 inches",
                            PStock = 50,
                            PStorage = "256 GB",
                            PWeight = "212 g"
                        },
                        new
                        {
                            PId = 7,
                            MId = 7,
                            PAvatar = "7.jpg",
                            PBatteryCapacity = "4500 mAh",
                            PCamera = "Triple camera: 12 MP + 12 MP + 12 MP",
                            PColor = "Frosted Black",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Sony",
                            PDimension = "165.0 x 71.0 x 8.2 mm",
                            PName = "Sony Xperia 1 III",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 1399m,
                            PPrice = 1299m,
                            PRam = "12 GB",
                            PResolution = "3840 x 1644 pixels",
                            PScreenSize = "6.5 inches",
                            PStock = 30,
                            PStorage = "256 GB",
                            PWeight = "186 g"
                        },
                        new
                        {
                            PId = 8,
                            MId = 8,
                            PAvatar = "8.jpg",
                            PBatteryCapacity = "4300 mAh",
                            PCamera = "Triple camera: 48 MP + 8 MP + 5 MP",
                            PColor = "Illusion Sunset",
                            PConnectivity = "5G",
                            PDescription = "Mid-range phone from LG",
                            PDimension = "167.2 x 74.1 x 7.9 mm",
                            PName = "LG Velvet 5G",
                            POperatingSystem = "Android 10",
                            POriginalPrice = 599m,
                            PPrice = 499m,
                            PRam = "6 GB",
                            PResolution = "2460 x 1080 pixels",
                            PScreenSize = "6.8 inches",
                            PStock = 100,
                            PStorage = "128 GB",
                            PWeight = "180 g"
                        },
                        new
                        {
                            PId = 9,
                            MId = 9,
                            PAvatar = "9.jpg",
                            PBatteryCapacity = "4470 mAh",
                            PCamera = "Quad camera: 64 MP + 5 MP + 2 MP + 2 MP",
                            PColor = "Midnight Sun",
                            PConnectivity = "5G",
                            PDescription = "Mid-range phone from Nokia",
                            PDimension = "168.9 x 79.7 x 9.1 mm",
                            PName = "Nokia X20",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 499m,
                            PPrice = 449m,
                            PRam = "8 GB",
                            PResolution = "2400 x 1080 pixels",
                            PScreenSize = "6.67 inches",
                            PStock = 150,
                            PStorage = "128 GB",
                            PWeight = "220 g"
                        },
                        new
                        {
                            PId = 10,
                            MId = 10,
                            PAvatar = "10.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Triple camera: 48 MP + 2 MP + 2 MP",
                            PColor = "Flash Gray",
                            PConnectivity = "4G",
                            PDescription = "Budget phone from Motorola",
                            PDimension = "165.3 x 75.9 x 9.5 mm",
                            PName = "Motorola Moto G Power (2022)",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 249m,
                            PPrice = 199m,
                            PRam = "4 GB",
                            PResolution = "1600 x 720 pixels",
                            PScreenSize = "6.6 inches",
                            PStock = 200,
                            PStorage = "64 GB",
                            PWeight = "206 g"
                        },
                        new
                        {
                            PId = 11,
                            MId = 1,
                            PAvatar = "11.jpg",
                            PBatteryCapacity = "4400 mAh",
                            PCamera = "Triple camera: 12 MP + 12 MP + 12 MP",
                            PColor = "Phantom Green",
                            PConnectivity = "5G",
                            PDescription = "Foldable flagship phone from Samsung",
                            PDimension = "158.2 x 128.1 x 6.4 mm",
                            PName = "Samsung Galaxy Z Fold 3",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 1999m,
                            PPrice = 1799m,
                            PRam = "12 GB",
                            PResolution = "2208 x 1768 pixels",
                            PScreenSize = "7.6 inches",
                            PStock = 50,
                            PStorage = "512 GB",
                            PWeight = "271 g"
                        },
                        new
                        {
                            PId = 12,
                            MId = 2,
                            PAvatar = "12.jpg",
                            PBatteryCapacity = "1821 mAh",
                            PCamera = "Single camera: 12 MP",
                            PColor = "Product Red",
                            PConnectivity = "4G",
                            PDescription = "Budget phone from Apple",
                            PDimension = "138.4 x 67.3 x 7.3 mm",
                            PName = "iPhone SE (2022)",
                            POperatingSystem = "iOS 15",
                            POriginalPrice = 449m,
                            PPrice = 399m,
                            PRam = "4 GB",
                            PResolution = "1334 x 750 pixels",
                            PScreenSize = "4.7 inches",
                            PStock = 100,
                            PStorage = "64 GB",
                            PWeight = "148 g"
                        },
                        new
                        {
                            PId = 13,
                            MId = 4,
                            PAvatar = "13.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Quad camera: 108 MP + 50 MP + 12 MP + 20 MP",
                            PColor = "Cosmic Black",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Xiaomi",
                            PDimension = "164.3 x 74.6 x 8.8 mm",
                            PName = "Xiaomi Mi 12",
                            POperatingSystem = "Android 12",
                            POriginalPrice = 1199m,
                            PPrice = 1099m,
                            PRam = "12 GB",
                            PResolution = "3200 x 1440 pixels",
                            PScreenSize = "6.81 inches",
                            PStock = 30,
                            PStorage = "256 GB",
                            PWeight = "205 g"
                        },
                        new
                        {
                            PId = 14,
                            MId = 11,
                            PAvatar = "14.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Triple camera: 50 MP + 48 MP + 12 MP",
                            PColor = "Stormy Black",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Google",
                            PDimension = "163.9 x 75.8 x 8.9 mm",
                            PName = "Google Pixel 6 Pro",
                            POperatingSystem = "Android 12",
                            POriginalPrice = 1199m,
                            PPrice = 1099m,
                            PRam = "12 GB",
                            PResolution = "3120 x 1440 pixels",
                            PScreenSize = "6.7 inches",
                            PStock = 50,
                            PStorage = "256 GB",
                            PWeight = "207 g"
                        },
                        new
                        {
                            PId = 15,
                            MId = 4,
                            PAvatar = "15.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Quad camera: 108 MP + 10 MP + 10 MP + 12 MP",
                            PColor = "Phantom Black",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Samsung with the best camera",
                            PDimension = "165.1 x 75.6 x 8.9 mm",
                            PName = "Samsung Galaxy S21 Ultra",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 1799m,
                            PPrice = 1599m,
                            PRam = "16 GB",
                            PResolution = "3200 x 1440 pixels",
                            PScreenSize = "6.8 inches",
                            PStock = 70,
                            PStorage = "512 GB",
                            PWeight = "229 g"
                        },
                        new
                        {
                            PId = 16,
                            MId = 13,
                            PAvatar = "16.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Triple camera: 64 MP + 8 MP + 2 MP",
                            PColor = "Black",
                            PConnectivity = "5G",
                            PDescription = "Mid-range phone from Realme",
                            PDimension = "158.5 x 73.3 x 8.4 mm",
                            PName = "Realme GT Neo 2",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 449m,
                            PPrice = 399m,
                            PRam = "8 GB",
                            PResolution = "2400 x 1080 pixels",
                            PScreenSize = "6.62 inches",
                            PStock = 100,
                            PStorage = "128 GB",
                            PWeight = "186 g"
                        },
                        new
                        {
                            PId = 17,
                            MId = 14,
                            PAvatar = "17.jpg",
                            PBatteryCapacity = "4600 mAh",
                            PCamera = "Triple camera: 64 MP + 64 MP + 64 MP",
                            PColor = "Black",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from ZTE",
                            PDimension = "161.5 x 73 x 8 mm",
                            PName = "ZTE Axon 30 Ultra",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 799m,
                            PPrice = 749m,
                            PRam = "12 GB",
                            PResolution = "2400 x 1080 pixels",
                            PScreenSize = "6.67 inches",
                            PStock = 80,
                            PStorage = "256 GB",
                            PWeight = "188 g"
                        },
                        new
                        {
                            PId = 18,
                            MId = 5,
                            PAvatar = "18.jpg",
                            PBatteryCapacity = "4500 mAh",
                            PCamera = "Quad camera: 50 MP + 48 MP + 8 MP + 2 MP",
                            PColor = "Morning Mist",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from OnePlus",
                            PDimension = "165.2 x 74.6 x 8.7 mm",
                            PName = "OnePlus 10 Pro",
                            POperatingSystem = "Android 12",
                            POriginalPrice = 1399m,
                            PPrice = 1299m,
                            PRam = "12 GB",
                            PResolution = "3216 x 1440 pixels",
                            PScreenSize = "6.7 inches",
                            PStock = 60,
                            PStorage = "512 GB",
                            PWeight = "199 g"
                        },
                        new
                        {
                            PId = 19,
                            MId = 5,
                            PAvatar = "19.jpg",
                            PBatteryCapacity = "4500 mAh",
                            PCamera = "Quad camera: 50 MP + 50 MP + 13 MP + 5 MP",
                            PColor = "Galactic Silver",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from OPPO",
                            PDimension = "163.6 x 74 x 8.26 mm",
                            PName = "OPPO Find X5 Pro",
                            POperatingSystem = "Android 12",
                            POriginalPrice = 1599m,
                            PPrice = 1499m,
                            PRam = "16 GB",
                            PResolution = "3216 x 1440 pixels",
                            PScreenSize = "6.7 inches",
                            PStock = 40,
                            PStorage = "512 GB",
                            PWeight = "190 g"
                        },
                        new
                        {
                            PId = 20,
                            MId = 12,
                            PAvatar = "20.jpg",
                            PBatteryCapacity = "4500 mAh",
                            PCamera = "Quad camera: 50 MP + 48MP + 12 MP + 8 MP",
                            PColor = "Orange",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Vivo",
                            PDimension = "164.8 x 75 x 9 mm",
                            PName = "Vivo X70 Pro+",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 1399m,
                            PPrice = 1299m,
                            PRam = "12 GB",
                            PResolution = "3200 x 1440 pixels",
                            PScreenSize = "6.78 inches",
                            PStock = 30,
                            PStorage = "512 GB",
                            PWeight = "209 g"
                        },
                        new
                        {
                            PId = 21,
                            MId = 13,
                            PAvatar = "21.jpg",
                            PBatteryCapacity = "4000 mAh",
                            PCamera = "Dual camera: 12 MP + 12 MP",
                            PColor = "Black",
                            PConnectivity = "4G",
                            PDescription = "Smartphone with a physical keyboard from BlackBerry",
                            PDimension = "151.4 x 71.8 x 8.5 mm",
                            PName = "BlackBerry KEY3",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 799m,
                            PPrice = 699m,
                            PRam = "6 GB",
                            PResolution = "1620 x 1080 pixels",
                            PScreenSize = "4.5 inches",
                            PStock = 20,
                            PStorage = "128 GB",
                            PWeight = "190 g"
                        },
                        new
                        {
                            PId = 22,
                            MId = 6,
                            PAvatar = "22.jpg",
                            PBatteryCapacity = "4600 mAh",
                            PCamera = "Quad camera: 50 MP + 64 MP + 13 MP + 3D ToF",
                            PColor = "Golden Hour",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from Honor",
                            PDimension = "162.8 x 74.9 x 9.5 mm",
                            PName = "Honor Magic 3",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 1099m,
                            PPrice = 999m,
                            PRam = "8 GB",
                            PResolution = "2772 x 1344 pixels",
                            PScreenSize = "6.76 inches",
                            PStock = 50,
                            PStorage = "256 GB",
                            PWeight = "203 g"
                        },
                        new
                        {
                            PId = 23,
                            MId = 14,
                            PAvatar = "23.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Triple camera: 108 MP + 24 MP + 12 MP",
                            PColor = "Aurora Black",
                            PConnectivity = "5G",
                            PDescription = "Flagship phone from LG",
                            PDimension = "166.4 x 76.1 x 8.8 mm",
                            PName = "LG V70 ThinQ",
                            POperatingSystem = "Android 12",
                            POriginalPrice = 1299m,
                            PPrice = 1199m,
                            PRam = "8 GB",
                            PResolution = "3200 x 1440 pixels",
                            PScreenSize = "6.8 inches",
                            PStock = 35,
                            PStorage = "256 GB",
                            PWeight = "189 g"
                        },
                        new
                        {
                            PId = 24,
                            MId = 7,
                            PAvatar = "24.jpg",
                            PBatteryCapacity = "4900 mAh",
                            PCamera = "Triple camera: 108 MP + 8 MP + 5 MP",
                            PColor = "Cosmic Black",
                            PConnectivity = "5G",
                            PDescription = "Mid-range phone from Xiaomi",
                            PDimension = "164.3 x 74.6 x 8.8 mm",
                            PName = "Xiaomi Mi Note 11",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 649m,
                            PPrice = 599m,
                            PRam = "6 GB",
                            PResolution = "2400 x 1080 pixels",
                            PScreenSize = "6.67 inches",
                            PStock = 90,
                            PStorage = "128 GB",
                            PWeight = "196 g"
                        },
                        new
                        {
                            PId = 25,
                            MId = 8,
                            PAvatar = "25.jpg",
                            PBatteryCapacity = "5000 mAh",
                            PCamera = "Triple camera: 108MP + 16 MP + 8 MP",
                            PColor = "Midnight Blue",
                            PConnectivity = "5G",
                            PDescription = "Mid-range phone from Motorola",
                            PDimension = "163.1 x 76.3 x 8.9 mm",
                            PName = "Motorola Edge 30",
                            POperatingSystem = "Android 11",
                            POriginalPrice = 549m,
                            PPrice = 499m,
                            PRam = "6 GB",
                            PResolution = "2400 x 1080 pixels",
                            PScreenSize = "6.7 inches",
                            PStock = 120,
                            PStorage = "128 GB",
                            PWeight = "185 g"
                        });
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.ProductInCategory", b =>
                {
                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.HasKey("CId", "PId");

                    b.HasIndex("PId");

                    b.ToTable("tbProductInCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CId = 1,
                            PId = 1
                        },
                        new
                        {
                            CId = 1,
                            PId = 2
                        },
                        new
                        {
                            CId = 2,
                            PId = 3
                        },
                        new
                        {
                            CId = 2,
                            PId = 4
                        },
                        new
                        {
                            CId = 3,
                            PId = 5
                        },
                        new
                        {
                            CId = 3,
                            PId = 6
                        },
                        new
                        {
                            CId = 4,
                            PId = 7
                        },
                        new
                        {
                            CId = 4,
                            PId = 8
                        },
                        new
                        {
                            CId = 4,
                            PId = 9
                        },
                        new
                        {
                            CId = 5,
                            PId = 10
                        },
                        new
                        {
                            CId = 5,
                            PId = 11
                        },
                        new
                        {
                            CId = 5,
                            PId = 12
                        },
                        new
                        {
                            CId = 6,
                            PId = 13
                        },
                        new
                        {
                            CId = 6,
                            PId = 14
                        },
                        new
                        {
                            CId = 7,
                            PId = 15
                        },
                        new
                        {
                            CId = 7,
                            PId = 16
                        },
                        new
                        {
                            CId = 7,
                            PId = 17
                        },
                        new
                        {
                            CId = 8,
                            PId = 18
                        },
                        new
                        {
                            CId = 8,
                            PId = 19
                        },
                        new
                        {
                            CId = 8,
                            PId = 20
                        });
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Order", b =>
                {
                    b.HasOne("PhoneShop.Data.Entities.Customer", "Customer")
                        .WithMany("OrderList")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("PhoneShop.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneShop.Data.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Product", b =>
                {
                    b.HasOne("PhoneShop.Data.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("MId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.ProductInCategory", b =>
                {
                    b.HasOne("PhoneShop.Data.Entities.Category", "Category")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneShop.Data.Entities.Product", "Product")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Category", b =>
                {
                    b.Navigation("ProductInCategories");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Customer", b =>
                {
                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PhoneShop.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ProductInCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
